name: notes_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Note.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Note.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
